apiVersion: v1
kind: Service
metadata:
  name: data-api
  labels:
    name: data-api
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3009
    targetPort: 3009
  selector:
    app: data-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-api
  template:
    metadata:
      labels:
        app: data-api
    spec:
      containers:
        - image: chzbrgr71/data-api:v1.1
        #- image: docker.pkg.github.com/chzbrgr71/service-tracker/data-api:v1.1
          imagePullPolicy: Always
          name: data-api
          env:
            - name: MONGODB_USER
              value: "dbuser"
            - name: MONGODB_PASSWORD
              value: "dbpassword"
            - name: MONGODB_IP
              value: "mongodb"
            - name: MONGODB_PORT
              value: "27017"
          ports:
          - containerPort: 3009
            protocol: TCP
      restartPolicy: Always
