apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  releaseName: rabbitmq
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: rabbitmq
    version: 8.9.2
  values:
    replicaCount: 3
    #service.type: LoadBalancer
    #auth.password: MyPassword123
    #auth.username: reddogadmin
    auth.existingPasswordSecret: rabbitmq-password
    podSecurityContext.enabled: true
    podSecurityContext.fsGroup: 2000
    podSecurityContext.runAsUser: 0