apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: orders
  namespace: reddog-retail
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "@every 5s"
scopes:
  - virtual-worker