apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reddog.binding.receipt
  namespace: reddog-retail
spec:
  type: bindings.azure.blobstorage
  version: v1
  metadata:
    - name: storageAccount
      secretKeyRef:
        name: storage-account-name
        key: storage-account-name
    - name: container
      secretKeyRef:
        name: storage-container-name
        key: storage-container-name
    - name: storageAccessKey
      secretKeyRef:
        name: blob-storage-key
        key: blob-storage-key
scopes:
  - receipt-generation-service
auth:
  secretStore: reddog.secretstore 
