apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reddog.secretstore
  namespace: reddog-retail
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
    - name: vaultName
      value: hub-kv-qfmva3vgu4w6q
    - name: spnClientId
      value: 610eb5a8-4272-4b58-aea7-b18b76bb377f
    - name: spnTenantId
      value: 72f988bf-86f1-41af-91ab-2d7cd011db47
    - name: spnCertificate
      secretKeyRef:
        name: reddog.secretstore
        key: secretstore-cert
