apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./components/reddog.config.yaml
- ./components/reddog.pubsub.yaml
- ./components/reddog.secretstore.yaml
- ./components/reddog.state.loyalty.yaml
- ./deployments/accounting-service.yaml
- ./deployments/bootstrapper.yaml
- ./deployments/loyalty-service.yaml
- ./deployments/rbac.yaml
