apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-service
  namespace: reddog-branch
  labels:
    app: loyalty-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyalty-service
  template:
    metadata:
      labels:
        app: loyalty-service
      annotations:
        dapr.io/enabled: 'true'
        dapr.io/app-id: loyalty-service
        dapr.io/app-port: '80'
        dapr.io/config: reddog.config
    spec:
      containers:
        - name: loyalty-service
          image: ghcr.io/azure/reddog-retail-demo/reddog-retail-loyalty-service:17fd371
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          startupProbe:
            httpGet:
              path: /probes/healthz
              port: 80
            failureThreshold: 6
            periodSeconds: 10
