apiVersion: apps/v1
kind: Deployment
metadata:
  name: receipt-generation-service
  namespace: reddog-retail
  labels:
    app: receipt-generation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receipt-generation-service
  template:
    metadata:
      labels:
        app: receipt-generation-service
      annotations:
        dapr.io/enabled: 'true'
        dapr.io/app-id: receipt-generation-service
        dapr.io/app-port: '80'
        dapr.io/config: reddog.config
    spec:
      containers:
        - name: receipt-generation-service
          image: ghcr.io/azure/reddog-retail-demo/reddog-retail-receipt-generation-service:b12e588
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          startupProbe:
            httpGet:
              path: /probes/healthz
              port: 80
            failureThreshold: 6
            periodSeconds: 10
