apiVersion: v1
kind: Service
metadata:
  name: reddog-retail-ui
  namespace: reddog-retail  
  labels:
    name: reddog-retail-ui
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8081
    targetPort: 8080
  selector:
    app: ui 
