apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reddog.secretstore
  namespace: reddog-retail
spec:
  metadata:
    - name: vaultName
      secretKeyRef:
        name: reddog.secretstore
        key: vaultName
    - name: spnClientId
      secretKeyRef:
        name: reddog.secretstore
        key: spnClientId
    - name: spnTenantId
      secretKeyRef:
        name: reddog.secretstore
        key: spnTenantId
    - name: spnCertificate
      secretKeyRef:
        name: reddog.secretstore
        key: secretstore-cert