apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reddog.secretstore
  namespace: <namespace>
spec:
  metadata:
    - name: vaultName
      value: <vaultName>
    - name: spnClientId
      value: <spnClientId>
    - name: spnTenantId
      value: <spnTenantId>
    - name: spnCertificate
      secretKeyRef:
        name: reddog.secretstore
        key: secretstore-cert