apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: reddog-retail
spec:
  template:
    spec:
      containers:
      - name: ui
        env:
        - name: NODE_ENV
          value: "production"
        - name: VUE_APP_IS_CORP
          value: "false"          
        - name: VUE_APP_STORE_ID
          value: <STORE_ID>
        - name: VUE_APP_SITE_TYPE
          value: <SITE_TYPE>
        - name: VUE_APP_SITE_TITLE
          value: <SITE_TITLE>
        - name: VUE_APP_MAKELINE_BASE_URL
          value: <MAKELINE_BASE_URL>
        - name: VUE_APP_ACCOUNTING_BASE_URL
          value: <ACCOUNTING_BASE_URL>
