apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reddog.secretstore
  namespace: reddog-retail
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
    - name: vaultName
      value: brian-reddog-hub-kvcorp
    - name: spnClientId
      value: c51e1dab-9cee-4f9b-99ef-fd973e7247c2
    - name: spnTenantId
      value: 72f988bf-86f1-41af-91ab-2d7cd011db47
    - name: spnCertificate
      secretKeyRef:
        name: reddog.secretstore
        key: secretstore-cert
