apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reddog.secretstore
  namespace: reddog-corp
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
    - name: vaultName
      value: reddog-kv-corp
    - name: spnClientId
      value: 
    - name: spnTenantId
      value: 
    - name: spnCertificate
      secretKeyRef:
        name: reddog.secretstore
        key: secretstore-cert
