apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reddog.pubsub
  namespace: reddog-retail
spec:
  type: pubsub.azure.servicebus
  version: v1  
  metadata:
    - name: connectionString
      secretKeyRef:
        name: sb-root-connectionstring
        key: sb-root-connectionstring
scopes:
  - loyalty-service
  - accounting-service 
auth:
  secretStore: reddog.secretstore
