apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reddog.secretstore
  namespace: contoso-health
spec:
  metadata:
    - name: vaultName
      value: contoso-kv-denver
    - name: spnClientId
      value: 8856410a-db9c-44fb-8877-118e9d4c7d9e
    - name: spnTenantId
      value: 72f988bf-86f1-41af-91ab-2d7cd011db47
    - name: spnCertificate
      secretKeyRef:
        name: reddog.secretstore
        key: secretstore-cert