apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: reddog-retail
spec:
  template:
    spec:
      containers:
      - name: ui
        env:
        - name: NODE_ENV
          value: "production"
        - name: VUE_APP_IS_CORP
          value: "false"          
        - name: VUE_APP_STORE_ID
          value: "Denver"
        - name: VUE_APP_SITE_TYPE
          value: "Pharmacy"
        - name: VUE_APP_SITE_TITLE
          value: "Contoso Health :: Denver"
        - name: VUE_APP_MAKELINE_BASE_URL
          value: "http://13.82.2.97:5200"
        - name: VUE_APP_ACCOUNTING_BASE_URL
          value: "http://13.82.2.97:5700"          
